envArtyProd/ArtyProd/ArtyProd/urls.py
from django.contrib import admin,auth
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'), name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='registration/logout.html'), name ='logout'),

]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

envArtyProd/ArtyProd/user/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth.views import (
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [	
    #service
    path('listSer/',views.listSer,name='listSer'),
    path('AddService/',views.AddService,name='AddService'),
    path('edit_Service/',views.edit_Service,name='edit_Service'),
    path('list/edit/<int:service_id>/', views.edit_Service, name='edit_Service'),
    path('view_service/',views.view_service,name='view_service'),
    path('list/<int:service_id>/view', views.view_service, name='view_service'),
    path('delete_service/',views.delete_service,name='delete_service'),
    path('list/<int:service_id>/Delete', views.delete_service, name='delete_service'),
    #register
    path('register/',views.register, name = 'register'), 
    #projet
    path('',views.listprojet,name='listprojet'),
    path('Addprojet/',views.Addprojet,name='Addprojet'),
    path('edit_projet/',views.edit_projet,name='edit_projet'),
    path('listp/edit/<int:projet_id>/', views.edit_projet, name='edit_projet'),
    path('view_projet/',views.view_projet,name='view_projet'),
    path('listp/<int:projet_id>/view', views.view_projet, name='view_projet'),
    path('delete_projet/',views.delete_projet,name='delete_projet'),
    path('listp/<int:projet_id>/DeleteProjet', views.delete_projet, name='delete_projet'),
    path('projets_acheves/', views.projets_acheves, name='projets_acheves'),
    path('projets_non_acheves/', views.projets_non_acheves, name='projets_non_acheves'),
    path('projet/release_equipe/<int:projet_id>/', views.release_equipe, name='release_equipe'),
    
    #personnel
    path('listPerson/',views.listPerson,name='listPerson'),
    path('personnel_create/',views.personnel_create,name='personnel_create'),
    path('personnel_edit/',views.personnel_edit,name='personnel_edit'),
    path('listpe/edit_personnel/<int:id>/', views.personnel_edit, name='personnel_edit'),
    path('personnel_delete/',views.personnel_delete,name='personnel_delete'),
    path('listpe/<int:id>/Delete_personnel', views.personnel_delete, name='personnel_delete'),
    path('view_personne/',views.view_personne,name='view_personne'),
    path('listpe/<int:id>/view_personnel', views.view_personne, name='view_personne'),

    #equipe
    path('listequipe/',views.listequipe,name='listequipe'),
    path('equipe_create/',views.equipe_create,name='equipe_create'),
    path('edit_team/',views.edit_team,name='edit_team'),
    path('delete_team/',views.delete_team,name='delete_team'),
    path('listq/<int:team_id>/edit', views.edit_team, name='edit_team'),
    path('listq/<int:team_id>/Delete', views.delete_team, name='delete_team'),
    #password-reset
    path('password-reset/', PasswordResetView.as_view(template_name='password_reset.html',html_email_template_name='password_reset_email.html'),name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),
    #contact
    path('contact/', views.contact, name='Contact'),
    path('send_mail/',views.send_email,name='send_email'),
    #ajouter project 
    path('projets/', views.projet_utilisateur_list, name='projet_utilisateurlist'),
    path('projetsajouter/', views.ajouter_projet_utilisateur, name='ajouterprojetutilisateur'),
    path('demandeprojet/',views.demandeproj,name='demandeproj'),
    path('send_emailproj/',views.send_emailproj,name='send_emailproj'),

    ]

envArtyProd/ArtyProd/user/models.py
from datetime import date
from django.db import models

from django.contrib.auth.models import User

class Service (models.Model):
    TYPE_CHOICES=[
        ('cg','Charte graphique '),
        ('ob','Objet  3D'),
        ('Sc','Scénarisation')
    ]
    type=models.CharField(max_length=2,choices=TYPE_CHOICES,default='em')
    description=models.TextField(default='Non définie')

    def __str__(self):
        return "type "+self.type+" description "+self.description
class Personnel(models.Model):
    nom=models.CharField(max_length=100)
    fichier_CV=models.FileField(blank=True,upload_to='media/')
    fichier_photo=models.ImageField(blank=True,upload_to='media/')
    lien_linkedln = models.URLField()
    
    def __str__(self):
        return "nom"+self.nom
class detail(models.Model):
    fichier=models.FileField(blank=True,upload_to='media/')
    service=models.ForeignKey('Service',on_delete=models.CASCADE,null=True)
    projet=models.ForeignKey('Projet',on_delete=models.CASCADE,null=True)
class Projet(models.Model):
    TYPE_CHOICES=[
        ('o','oui'),
        ('n','non'),
    ]
    libellé=models.CharField(max_length=100)
    description=models.TextField(default='Non définie')
    date_debut = models.DateField()
    date_fin = models.DateField()
    acheve=models.CharField(max_length=1,choices=TYPE_CHOICES,default='n')
    img=models.ImageField(blank=True,upload_to='media/')
    service=models.ManyToManyField('Service',through="detail")
    equipe=models.OneToOneField('Equipe',on_delete=models.CASCADE,null=True)
    def save(self, *args, **kwargs):
        if self.acheve == 'o' and self.equipe is not None:
            self.equipe = None
        super().save(*args, **kwargs)
class Equipe(models.Model):
    nom=models.CharField(default='non définie',max_length=100)
    personnels=models.ManyToManyField('Personnel')
    def __str__(self):
        personnel_list = ", ".join(personnel.nom for personnel in self.personnels.all())
        i=self.id
        return f"Equipe {i} : ({personnel_list})"
class ProjetUtilisateur(models.Model):
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)
    projet = models.ManyToManyField(Projet)

    def __str__(self):
        return " "+self.projet.libellé  +" "+str(self.projet.date_fin)+" "+str(self.utilisateur.username)
# class User(AbstractUser):
#     nom=models.CharField(max_length=100)
#     fichier_photo = models.FileField()

envArtyProd/ArtyProd/user/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .forms import *
from .models import *
from django.http import HttpResponseRedirect
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponse


#service
def listSer(request):
    list=Service.objects.all()
    return render(request, 'service/affiche_service.html',{'list':list})

def AddService(request):
    if request.method == "POST":
        form = ServiceForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('listSer')
    else:
        form = ServiceForm()
    service = Service.objects.all()
    return render(request, 'service/AddS.html', {'service': service, 'form': form})

def edit_Service(request, service_id):
    service = Service.objects.get(id=service_id)
    form = ServiceForm(instance=service)
    
    if request.method == 'POST':
        form = ServiceForm(request.POST, instance=service)
        if form.is_valid():
            form.save()
            return redirect('listSer')
    
    return render(request, 'service/edit_service.html', {'form': form, 'service': service})

def view_service(request, service_id):
    service = get_object_or_404(Service, id=service_id)
    return render(request, 'service/service_detail.html', {'service': service})

def delete_service(request, service_id):
    # Récupérer le service correspondant à l'identifiant unique donné
    service = get_object_or_404(Service, id=service_id)

    if request.method == 'POST':
        # Supprimer le service de la base de données
        service.delete()
        return redirect('listSer')
    return render(request, 'service/delete_service.html', {'service': service})
#register
def register(request):
    if request.method == 'POST' :  
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request,user)
            messages.success(request, f'Coucou {username}, Votre compte a été créé avec succès !')
            return redirect('login')
    else :
        form = UserRegistrationForm()
    return render(request,'registration/register.html',{'form' : form})

#projet
def listprojet(request):
    listp=Projet.objects.all()
    return render(request, 'projet/affiche_projet.html',{'listp':listp})
def Addprojet(request):
    if request.method == "POST":
        form = ProjetForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('listprojet')
    else:
        form = ProjetForm()
    projet = Projet.objects.all()
    return render(request, 'projet/AddP.html', {'projet': projet, 'form': form})
def edit_projet(request, projet_id):
    projet = Projet.objects.get(id=projet_id)
    form = ProjetForm(instance=projet)
    
    if request.method == 'POST':
        form = ProjetForm(request.POST, instance=projet)
        if form.is_valid():
            form.save()
            return redirect('listprojet')
    
    return render(request, 'projet/edit_projet.html', {'form': form, 'projet': projet})
def view_projet(request, projet_id):
    projet = get_object_or_404(Projet, id=projet_id)
    return render(request, 'projet/projet_detail.html', {'projet': projet})

def delete_projet(request, projet_id):
    # Récupérer le service correspondant à l'identifiant unique donné
    projet = get_object_or_404(Projet, id=projet_id)

    if request.method == 'POST':
        # Supprimer le service de la base de données
        projet.delete()
        return redirect('listprojet')
    return render(request, 'projet/delete_projet.html', {'projet': projet})


def projets_acheves(request):
    projets = Projet.objects.filter(acheve='o')
    return render(request, 'projet/affiche_acheve.html', {'projets': projets})

def projets_non_acheves(request):
    projets = Projet.objects.filter(acheve='n')
    return render(request, 'projet/affiche_nonacheve.html', {'projets': projets})
def release_equipe(request, projet_id):
    projet = get_object_or_404(Projet, id=projet_id)
    if projet.acheve == 'o' and projet.equipe is not None:
        projet.equipe = None
        projet.save()
        # Additional logic or rendering if needed
        return render(request, 'projet/release_success.html')
    else:
        # Additional logic or rendering if needed
        return render(request, 'projet/release_failure.html')

#personnel
def listPerson(request):
    listpe=Personnel.objects.all()
    return render(request,'personnel/mesPersonnel.html',{'listpe':listpe})
def personnel_create(request):
    if request.method == 'POST':
        form = PersonnelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('listPerson')
    else:
        form = PersonnelForm()
    personne=Personnel.objects.all()
    return render(request, 'personnel/addPersonnel.html', {'personne': personne,'form': form})
def personnel_edit(request,id):
    post = get_object_or_404(Personnel, id=id)
    if request.method == 'GET':
        context = {'form': PersonnelForm(instance=post), 'id': id}
        return render(request,'personnel/editPersonnel.html',context)
    elif request.method == 'POST':
        form = PersonnelForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('listPerson')
        else:
            return render(request,'personnel/editPersonnel.html',{'form':form})        
def personnel_delete(request, id):
    personnel = get_object_or_404(Personnel, pk=id)
    context = {'personnel': personnel}    
    if request.method == 'GET':
        return render(request, 'personnel/deletePersonnel.html',context)
    elif request.method == 'POST':
        personnel.delete()
        return redirect('listPerson')
def view_personne(request, id):
    personnel = get_object_or_404(Personnel, id=id)
    return render(request, 'personnel/personnel_detail.html', {'personnel': personnel})
#equipe
def listequipe(request):
    listq=Equipe.objects.all()
    return render(request,'equipe/afficheequipe.html',{'listq':listq})

"""def create_equipe(nom, personnel_list):
    equipe = Equipe.objects.create(nom=nom)
    for personnel in personnel_list:
        equipe.personnel.add(personnel)
    equipe.save()
    return equipe"""
def equipe_create(request):
    if request.method == 'POST':
        form = EquipeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('listequipe')
    else:
        form = EquipeForm()
    equipe=Equipe.objects.all()
    return render(request, 'equipe/addequipe.html', {'equipe': equipe,'form': form})
def edit_team(request, team_id):
    team = get_object_or_404(Equipe, id=team_id)
    if request.method == 'POST':
        form = EquipeForm(request.POST, instance=team)
        if form.is_valid():
            form.save()
            return redirect('listequipe')
    else:
        form = EquipeForm(instance=team)
    return render(request, 'equipe/edit_equipe.html', {'form': form})

def delete_team(request, team_id):
    team = get_object_or_404(Equipe, id=team_id)
    if request.method == 'POST':
        team.delete()
        return redirect('listequipe')
    return render(request, 'equipe/delete_equipe.html', {'team': team})
#contact
def contact(request):
     return render(request,'Contact/contact.html')

def send_email(request):
	if request.method == 'POST':
		name = request.POST.get('name')
		email = request.POST.get('email')
		subject = request.POST.get('subject')
		message = request.POST.get('message')
		send_mail(
			subject,
			'Contact from ' + name + ' (' + email + ')\n\n' + message,
			email,
			['adamkhabou719@gmail.com'],
			fail_silently=False,
		)
		return render(request,'Contact/contact.html',{'name':name})
	return render(request, 'Contact/contact.html')

def projet_utilisateur_list(request):
    projetutilisateurs = ProjetUtilisateur.objects.filter(utilisateur=request.user)
    context = {'projetutilisateurs': projetutilisateurs}
    return render(request, 'projet utilisateur/projet_utilisateur_list.html', context)
def ajouter_projet_utilisateur(request):
    if request.method == 'POST':
        form = ProjetUtilisateurForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('projet_utilisateurlist')
    else:
        form = ProjetUtilisateurForm()
    return render(request, 'projet utilisateur/ajouter_projet_utilisateur.html', {'form': form})

def demandeproj(request):
     return render(request,'projet utilisateur/demande_projet.html')
from django.core.mail import send_mail

def send_emailproj(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        projname = request.POST.get('projname')
        description = request.POST.get('description')
        date_fin = request.POST.get('date_fin')
        imageproj = request.POST.get('imageproj')
        serviceproj = request.POST.get('serviceproj')
        
        send_mail(
            projname,
            'Contact from ' + name + ' (' + email + ')\n\n' + description +'\n date fin '+date_fin+'\n image '+imageproj+'\n service '+serviceproj,
            email,
            ['adamkhabou719@gmail.com'],
            fail_silently=False,
        )
        return render(request, 'projet utilisateur/demande_projet.html', {'name': name})
    
    return render(request, 'projet utilisateur/demande_projet.html')

envArtyProd/ArtyProd/user/templates/projet utilisateur/ajouter_projet_utilisateur.html
{% include 'base.html' %} {% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/custom.css' %}" /> <!-- Fichier CSS personnalisé -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<style>
  .post-form {
    max-width: 500px;
    margin: 0 auto;
  }

  .post-form input[type="text"],
  .post-form input[type="text"],
  .post-form textarea {
    padding: 10px;
    margin-bottom: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
    box-sizing: border-box;
    height: 50px;
  }

  .post-form input[type="text"]:focus,
  .post-form input[type="text"]:focus,
  .post-form textarea:focus {
    outline: none;
    border: 2px solid #4caf50;
  }

  .post-form label {
    font-weight: bold;
  }

  .post-form button[type="submit"] {
    margin-top: 20px;
    font-size: 18px;
    font-weight: bold;
    color: #fff;
    background-color: #4caf50;
    border: none;
    border-radius: 5px;
    padding: 10px 20px;
    transition: all 0.3s ease;
  }

  .post-form button[type="submit"]:hover {
    background-color: #2e8b57;
    cursor: pointer;
  }
  fieldset {
    white: 20px;
    border: 3px solid #ccc;
    padding: 20px;
    border-radius: 5px;
  }

  fieldset legend {
    font-size: 24px;
    font-weight: bold;
    margin-bottom: 20px;
  }
  body {
    background-image: url("{% static 'css/image4.png' %}");
    background-size: cover; /* Ajuster la taille de l'image pour couvrir tout le corps */
    background-position: center; /* Centrer l'image horizontalement et verticalement */
  }
</style>

<div class="col-md-12 text-center"></div>
<fieldset border="2">
  <legend>Ajouter Projet</legend>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Ajouter</button>
</form>
  
  

</fieldset>
{% endblock %}

envArtyProd/ArtyProd/user/templates/projet utilisateur/demande_projet.html
{% include 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/custom.css' %}" /> <!-- Fichier CSS personnalisé -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<style>
  .btn-outline-danger:hover {
    background-color: white;
    border-color: red;
    color: white;
  }
  body {
    background-color: #f1f1f1;
  }
  img{
    height:200px
  }
</style>
{% block content %}
<div class="container">
	{% if name %}
	<center><h2>Thanks {{ name }}!</h2>
		<p>We received your project demande and will repond shortly...</p>
		</center>
		<br/><br/>
	{% endif %}

	  <div class="col-md-6">
      <form action="{% url 'send_emailproj' %}" method="POST">
		<h1>Demande de projet</h1>
        {% csrf_token %}
        <div class="form-group">
          <label for="name">Nom</label>
          <input
            type="text"
            class="form-control"
            id="name"
            name="name"
            placeholder="Entrez votre nom"
          />
        </div>
        <div class="form-group">
          <label for="email">Adresse e-mail</label>
          <input
            type="email"
            class="form-control"
            id="email"
            name="email"
            placeholder="Entrez votre adresse e-mail"
          />
        </div>
        <div class="form-group">
          <label for="projname">Nom de Projet</label>
          <input
            type="text"
            class="form-control"
            id="projname"
            name="projname"
            placeholder="Entrez le nom de votre projet"
          />
        </div>
        <div class="form-group">
          <label for="description">description du projet</label>
          <textarea
            class="form-control"
            id="description"
            name="description"
            rows="5"
          ></textarea>
        </div>
        <div class="form-group">
            <label for="date_fin">Date finale que vous souhaiter le projet se termine</label>
            <input
            type="date"
            class="form-controln"
            id="date_fin"
            name="date_fin"
          />
          </div>
          <div class="form-group">
            <label for="imageproj">Image de projet</label>
            <input
            type="file"
            class="form-control"
            id="imageproj"
            name="imageproj"
          />
          </div>
          <div class="form-group">
            <label for="serviceproj">Service de projet</label>
            <input
            type="text"
            class="form-control"
            id="serviceproj"
            name="serviceproj"
            placeholder="(Charte graphique)(Objet 3D)(Scénarisation)"
          />
          </div>
        <button type="submit" class="btn btn-primary">Envoyer</button>
      </form>
    </div>
  </div>
  </div>
</div>
{% endblock content %}

envArtyProd/ArtyProd/user/templates/projet utilisateur/projet_utilisateur_list.html
{% include 'base.html' %} {% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/custom.css' %}" />
<!-- Fichier CSS personnalisé -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<style>
  .btn-outline-danger:hover {
    background-color: white;
    border-color: red;
    color: white;
  }
  body {
    background-color: #f1f1f1;
  }
  img {
    height: 200px;
  }
</style>
{% block content %}

<div class="container my-5">
  <div class="row">
    {% for projetutilisateur in projetutilisateurs %}
     {% for projet in projetutilisateur.projet.all %}
    <div class="col-12 col-sm-6 col-md-4 mb-4">
      <div class="card">
        <img
        src='/media/{{ projet.img }}'
          class="card-img-top custom-img"
        />
        <!-- Ajout de la classe "custom-img" -->
        <div class="card-body">
          <h5 class="card-title">{{ projet.libellé }}</h5>
          <p class="card-text">{{ projet.description }}</p>
          <p class="card-text">Date de début: {{ projet.date_debut }}</p>
          <p class="card-text">Date de fin: {{ projet.date_fin }}</p>
          <p class="card-text">Statut: {{ projet.get_acheve_display }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
     {% endfor %}
  </div>
</div>

{% endblock %}